// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TimeHacker.Migrations.Factory;

#nullable disable

namespace TimeHacker.Migrations.Migrations
{
    [DbContext(typeof(TimeHackerMigrationsDbContext))]
    partial class TimeHackerMigrationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TimeHacker.Domain.Entities.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(516)
                        .HasColumnType("character varying(516)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ScheduleEntityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleEntityId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.Categories.CategoryDynamicTask", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DynamicTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoryId", "DynamicTaskId");

                    b.HasIndex("DynamicTaskId");

                    b.ToTable("CategoryDynamicTask");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.Categories.CategoryFixedTask", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FixedTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoryId", "FixedTaskId");

                    b.HasIndex("FixedTaskId");

                    b.ToTable("CategoryFixedTask");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.ScheduleSnapshots.ScheduleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LastEntityCreated")
                        .HasColumnType("date");

                    b.Property<byte[]>("RepeatingEntity")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EndsOn");

                    b.HasIndex("UserId");

                    b.ToTable("ScheduleEntity");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.ScheduleSnapshots.ScheduleSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("UserId");

                    b.ToTable("ScheduleSnapshot");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.ScheduleSnapshots.ScheduledCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("End")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentScheduleEntity")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("Start")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentScheduleEntity");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("ScheduledCategory");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.ScheduleSnapshots.ScheduledTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("End")
                        .HasColumnType("interval");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFixed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentScheduleEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParentTaskId")
                        .HasColumnType("uuid");

                    b.Property<byte>("Priority")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("ScheduledCategoryId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("Start")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsCompleted");

                    b.HasIndex("ParentScheduleEntityId");

                    b.HasIndex("ScheduledCategoryId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("ScheduledTask");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.Tags.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("UserId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.Tags.TagDynamicTask", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("TagId", "TaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("TagDynamicTask");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.Tags.TagFixedTask", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("TagId", "TaskId");

                    b.HasIndex("TaskId");

                    b.ToTable("TagFixedTask");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.Tasks.DynamicTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(516)
                        .HasColumnType("character varying(516)");

                    b.Property<TimeSpan>("MaxTimeToFinish")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("MinTimeToFinish")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<TimeSpan?>("OptimalTimeToFinish")
                        .HasColumnType("interval");

                    b.Property<byte>("Priority")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTimestamp");

                    b.HasIndex("UserId");

                    b.ToTable("DynamicTask");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.Tasks.FixedTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(516)
                        .HasColumnType("character varying(516)");

                    b.Property<DateTime>("EndTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<byte>("Priority")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("ScheduleEntityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedTimestamp");

                    b.HasIndex("ScheduleEntityId")
                        .IsUnique();

                    b.HasIndex("StartTimestamp");

                    b.HasIndex("UserId");

                    b.ToTable("FixedTask");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(450)
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailForNotifications")
                        .HasColumnType("text");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PhoneNumberForNotifications")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.Categories.Category", b =>
                {
                    b.HasOne("TimeHacker.Domain.Entities.ScheduleSnapshots.ScheduleEntity", "ScheduleEntity")
                        .WithOne("Category")
                        .HasForeignKey("TimeHacker.Domain.Entities.Categories.Category", "ScheduleEntityId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("TimeHacker.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleEntity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.Categories.CategoryDynamicTask", b =>
                {
                    b.HasOne("TimeHacker.Domain.Entities.Categories.Category", "Category")
                        .WithMany("CategoryDynamicTasks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("TimeHacker.Domain.Entities.Tasks.DynamicTask", "DynamicTask")
                        .WithMany("CategoryDynamicTasks")
                        .HasForeignKey("DynamicTaskId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("DynamicTask");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.Categories.CategoryFixedTask", b =>
                {
                    b.HasOne("TimeHacker.Domain.Entities.Categories.Category", "Category")
                        .WithMany("CategoryFixedTasks")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("TimeHacker.Domain.Entities.Tasks.FixedTask", "FixedTask")
                        .WithMany("CategoryFixedTasks")
                        .HasForeignKey("FixedTaskId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("FixedTask");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.ScheduleSnapshots.ScheduleEntity", b =>
                {
                    b.HasOne("TimeHacker.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.ScheduleSnapshots.ScheduleSnapshot", b =>
                {
                    b.HasOne("TimeHacker.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.ScheduleSnapshots.ScheduledCategory", b =>
                {
                    b.HasOne("TimeHacker.Domain.Entities.ScheduleSnapshots.ScheduleEntity", "ScheduleEntity")
                        .WithMany("ScheduledCategories")
                        .HasForeignKey("ParentScheduleEntity")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("TimeHacker.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeHacker.Domain.Entities.ScheduleSnapshots.ScheduleSnapshot", "ScheduleSnapshot")
                        .WithMany("ScheduledCategories")
                        .HasForeignKey("UserId", "Date")
                        .HasPrincipalKey("UserId", "Date")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("ScheduleEntity");

                    b.Navigation("ScheduleSnapshot");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.ScheduleSnapshots.ScheduledTask", b =>
                {
                    b.HasOne("TimeHacker.Domain.Entities.ScheduleSnapshots.ScheduleEntity", "ScheduleEntity")
                        .WithMany("ScheduledTasks")
                        .HasForeignKey("ParentScheduleEntityId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("TimeHacker.Domain.Entities.ScheduleSnapshots.ScheduledCategory", "ScheduledCategory")
                        .WithMany("ScheduledTasks")
                        .HasForeignKey("ScheduledCategoryId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("TimeHacker.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TimeHacker.Domain.Entities.ScheduleSnapshots.ScheduleSnapshot", "ScheduleSnapshot")
                        .WithMany("ScheduledTasks")
                        .HasForeignKey("UserId", "Date")
                        .HasPrincipalKey("UserId", "Date")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("ScheduleEntity");

                    b.Navigation("ScheduleSnapshot");

                    b.Navigation("ScheduledCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.Tags.Tag", b =>
                {
                    b.HasOne("TimeHacker.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.Tags.TagDynamicTask", b =>
                {
                    b.HasOne("TimeHacker.Domain.Entities.Tags.Tag", "Tag")
                        .WithMany("TagDynamicTasks")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("TimeHacker.Domain.Entities.Tasks.DynamicTask", "Task")
                        .WithMany("TagDynamicTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.Tags.TagFixedTask", b =>
                {
                    b.HasOne("TimeHacker.Domain.Entities.Tags.Tag", "Tag")
                        .WithMany("TagFixedTasks")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("TimeHacker.Domain.Entities.Tasks.FixedTask", "Task")
                        .WithMany("TagFixedTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.Tasks.DynamicTask", b =>
                {
                    b.HasOne("TimeHacker.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.Tasks.FixedTask", b =>
                {
                    b.HasOne("TimeHacker.Domain.Entities.ScheduleSnapshots.ScheduleEntity", "ScheduleEntity")
                        .WithOne("FixedTask")
                        .HasForeignKey("TimeHacker.Domain.Entities.Tasks.FixedTask", "ScheduleEntityId")
                        .OnDelete(DeleteBehavior.ClientCascade);

                    b.HasOne("TimeHacker.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleEntity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.Categories.Category", b =>
                {
                    b.Navigation("CategoryDynamicTasks");

                    b.Navigation("CategoryFixedTasks");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.ScheduleSnapshots.ScheduleEntity", b =>
                {
                    b.Navigation("Category");

                    b.Navigation("FixedTask");

                    b.Navigation("ScheduledCategories");

                    b.Navigation("ScheduledTasks");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.ScheduleSnapshots.ScheduleSnapshot", b =>
                {
                    b.Navigation("ScheduledCategories");

                    b.Navigation("ScheduledTasks");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.ScheduleSnapshots.ScheduledCategory", b =>
                {
                    b.Navigation("ScheduledTasks");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.Tags.Tag", b =>
                {
                    b.Navigation("TagDynamicTasks");

                    b.Navigation("TagFixedTasks");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.Tasks.DynamicTask", b =>
                {
                    b.Navigation("CategoryDynamicTasks");

                    b.Navigation("TagDynamicTasks");
                });

            modelBuilder.Entity("TimeHacker.Domain.Entities.Tasks.FixedTask", b =>
                {
                    b.Navigation("CategoryFixedTasks");

                    b.Navigation("TagFixedTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
