using System.Diagnostics;
using System.Diagnostics.Metrics;

namespace TimeHacker.Domain.Observability;

/// <summary>
/// Shared telemetry primitives for TimeHacker's application-level instrumentation. Lives in the Domain
/// layer so both the Application and Domain.Services layers can emit against a single <see cref="ActivitySource"/>
/// and <see cref="Meter"/>. The names below are registered with the OpenTelemetry SDK in the API's
/// <c>AddOpenTelemetry</c> wiring (<c>AddSource</c> / <c>AddMeter</c>).
/// </summary>
public static class TimeHackerTelemetry
{
    public const string ActivitySourceName = "TimeHacker";
    public const string MeterName = "TimeHacker";

    /// <summary>Business spans (e.g. timeline generation) nested inside the ambient request trace.</summary>
    public static readonly ActivitySource ActivitySource = new(ActivitySourceName);

    // internal (not private) so ActiveUserTracker can register its observable gauge on the same meter.
    internal static readonly Meter Meter = new(MeterName);

    /// <summary>
    /// Count of day-timeline requests, tagged <c>outcome = snapshot_hit | generated</c> — how many days are
    /// served from a stored snapshot versus regenerated.
    /// </summary>
    public static readonly Counter<long> SnapshotRequests =
        Meter.CreateCounter<long>("timehacker.snapshots.requested", unit: "{request}",
            description: "Day-timeline requests, split by whether an existing snapshot was reused or a new one generated.");

    /// <summary>Wall-clock duration of the timeline-generation algorithm for a single day, in milliseconds.</summary>
    public static readonly Histogram<double> TimelineGenerationDuration =
        Meter.CreateHistogram<double>("timehacker.timeline.generation.duration", unit: "ms",
            description: "Duration of generating a single day's timeline (snapshot miss path).");

    /// <summary>Number of scheduled task instances produced by timeline generation.</summary>
    public static readonly Counter<long> ScheduledTasksGenerated =
        Meter.CreateCounter<long>("timehacker.scheduled_tasks.generated", unit: "{task}",
            description: "Scheduled task instances produced while generating timelines.");

    /// <summary>Count of explicit, user-triggered snapshot regenerations (the refresh endpoint).</summary>
    public static readonly Counter<long> SnapshotsRefreshed =
        Meter.CreateCounter<long>("timehacker.snapshots.refreshed", unit: "{snapshot}",
            description: "Snapshots discarded and regenerated by an explicit refresh request.");

    /// <summary>
    /// Dynamic tasks seen by the timeline processor, tagged <c>outcome = placed | unplaced</c> — whether the
    /// gap-filling algorithm found room for the task in the generated day. The scheduling-quality signal.
    /// </summary>
    public static readonly Counter<long> DynamicTasksScheduled =
        Meter.CreateCounter<long>("timehacker.timeline.dynamic_tasks", unit: "{task}",
            description: "Dynamic tasks considered per generated day, split by whether they were placed in the timeline.");

    /// <summary>
    /// Fraction (0-1) of a generated day covered by scheduled tasks. The unit is the annotation
    /// <c>{ratio}</c> rather than <c>1</c> so the OTLP-to-Prometheus translation leaves the metric name
    /// alone (annotations in braces are dropped; <c>1</c> would append a <c>_ratio</c> suffix).
    /// </summary>
    public static readonly Histogram<double> DayUtilization =
        Meter.CreateHistogram<double>("timehacker.timeline.day_utilization", unit: "{ratio}",
            description: "Share of a generated day occupied by tasks, between 0 and 1.");

    /// <summary>Recurrence occurrences materialized into concrete tasks, tagged by repeating type.</summary>
    public static readonly Counter<long> ScheduleEntitiesExpanded =
        Meter.CreateCounter<long>("timehacker.schedule_entities.expanded", unit: "{occurrence}",
            description: "Recurrence occurrences expanded into task instances, by repeating-entity type.");

    /// <summary>
    /// Business exceptions surfaced to clients, tagged with the exception type and the status code it maps
    /// to. <c>DbUpdateConcurrencyException</c> here doubles as the RLS cross-user-mutation signal.
    /// </summary>
    public static readonly Counter<long> BusinessExceptions =
        Meter.CreateCounter<long>("timehacker.business_exceptions", unit: "{exception}",
            description: "Handled business-logic exceptions, by exception type and resulting HTTP status.");

    /// <summary>Domain users provisioned on their first authenticated request — the signup event.</summary>
    public static readonly Counter<long> UsersRegistered =
        Meter.CreateCounter<long>("timehacker.users.registered", unit: "{user}",
            description: "Domain users created on first login.");

    public const string OutcomeSnapshotHit = "snapshot_hit";
    public const string OutcomeGenerated = "generated";
    public const string OutcomePlaced = "placed";
    public const string OutcomeUnplaced = "unplaced";

    public const string OutcomeTagName = "outcome";

    /// <summary>
    /// Metrics must never carry a user id — it is unbounded and would explode series cardinality. Per-user
    /// breakdowns come from spans (<c>enduser.id</c>) and log records, where high cardinality is free; the
    /// only user-shaped metric is the aggregate in <see cref="ActiveUserTracker"/>.
    /// </summary>
    public const string EndUserIdTagName = "enduser.id";
}
